sbnanaobj/StandardRecord/CMakeLists.txt

Rename SO to fullpath, indentation whitespace removal

---

sbnanaobj/StandardRecord/SREnums.h

Match more G4 processes. Include an explicit unknown process.

---

sbnanaobj/StandardRecord/SRTrueInteraction.cxx
sbnanaobj/StandardRecord/SRTrueInteraction.h
sbnanaobj/StandardRecord/SRTruthMatch.cxx
sbnanaobj/StandardRecord/SRTruthMatch.h

Fix variables which were mistakenly moved inside the SR-structure.

---

sbnanaobj/StandardRecord/SRTrack.h

Small updates to CAF. Add in direction to SRTrack object.

---

sbnanaobj/StandardRecord/SRTrueInteraction.cxx
sbnanaobj/StandardRecord/SRTrueInteraction.h

Filled by the corresponding branch in sbncode.

Add additional truth information that will be useful for xsec analyses

---

sbnanaobj/StandardRecord/SRLorentzVector.h
sbnanaobj/StandardRecord/SRVector3D.h

Should slightly speed up SRProxy generation, and hopefully render us immune to ROOT configuration settings.

Update existing GCCXML guards to castxml, and add them in SRVector3D

---

sbnanaobj/StandardRecord/classes_def.xml

Somehow got no complains about this before it got merged.

Checksum update

---

sbnanaobj/StandardRecord/SREnums.h
sbnanaobj/StandardRecord/SRMeVPrtl.cxx
sbnanaobj/StandardRecord/SRMeVPrtl.h
sbnanaobj/StandardRecord/SRTruthBranch.cxx
sbnanaobj/StandardRecord/SRTruthBranch.h
sbnanaobj/StandardRecord/classes_def.xml

Add in objects for MeVPrtl info to StandardRecord.

---

sbnanaobj/StandardRecord/SREnums.h

Needed to add a missing G4 process as part of the migration to the new LArG4

adding a missing g4 process

---

sbnanaobj/StandardRecord/SRCRTHit.cxx
sbnanaobj/StandardRecord/SRCRTHit.h
sbnanaobj/StandardRecord/SRTrack.cxx
sbnanaobj/StandardRecord/SRTrueParticle.cxx

Hlay initialisations

---

sbnanaobj/StandardRecord/SREnums.h

Requires: https://github.com/SBNSoftware/sbncode/pull/215

adding missing GEANT processes to CAFs

---

sbnanaobj/StandardRecord/SRBNBInfo.cxx
sbnanaobj/StandardRecord/SRBNBInfo.h
sbnanaobj/StandardRecord/SRHeader.cxx
sbnanaobj/StandardRecord/SRHeader.h
sbnanaobj/StandardRecord/classes_def.xml

goes with [SBNSoftware/sbncode](https://github.com/SBNSoftware/sbncode/pull/226)

production CAF fix

---

ups/product_deps

This latest version has a nice speedup for reading large arrays from flatcafs.

Bump srproxy version

---

sbnanaobj/StandardRecord/SRCRTHit.cxx
sbnanaobj/StandardRecord/SRCRTHit.h
sbnanaobj/StandardRecord/SRCRTTrackMatch.cxx
sbnanaobj/StandardRecord/SRCRTTrackMatch.h
sbnanaobj/StandardRecord/SRShowerRazzle.h
sbnanaobj/StandardRecord/SRTrack.h
sbnanaobj/StandardRecord/SRTrackDazzle.h
sbnanaobj/StandardRecord/SRTrackScatterClosestApproach.h
sbnanaobj/StandardRecord/SRTrackStoppingChi2Fit.h
sbnanaobj/StandardRecord/SRTrackTruth.h
sbnanaobj/StandardRecord/SRTrueParticle.h
sbnanaobj/StandardRecord/SRWeightMapEntry.h
sbnanaobj/StandardRecord/StandardRecord.cxx

Remove unnecessary includes, and move others into the .cxx. Use explicit paths within sbnanaobj/ everywhere.

Clean up sbnanaobj headers

---

sbnanaobj/StandardRecord/SRCRTHit.h
sbnanaobj/StandardRecord/classes_def.xml

Related to https://github.com/SBNSoftware/sbncode/pull/251

Adding t0 ana t1 in SRCRTHit

---

sbnanaobj/StandardRecord/classes_def.xml

Follow up develop version to #54

Add enums to classes_def

---

sbnanaobj/StandardRecord/SRCRTPMTMatch.cxx
sbnanaobj/StandardRecord/SRCRTPMTMatch.h
sbnanaobj/StandardRecord/StandardRecord.h
sbnanaobj/StandardRecord/classes_def.xml

This is a duplicate of PR #95 for production release

add CRTPMT Matching variables to the StandardRecord (production) 

---

sbnanaobj/StandardRecord/SRSlice.h
sbnanaobj/StandardRecord/classes_def.xml

Add charge center in width into SRSlice for the production branch. Associated with sbncode [PR #376](https://github.com/SBNSoftware/sbncode/pull/376).

Fill slice barycenter in production branch, take 2

---

sbnanaobj/StandardRecord/SRHeader.h
sbnanaobj/StandardRecord/classes_def.xml

Twin of PR #98, but for production branch.
In bundle with SBNSoftware/sbncode#366.

Added source file information to the standard record header [release; 1/2]

---

sbnanaobj/StandardRecord/SRCNNScore.cxx
sbnanaobj/StandardRecord/SRCNNScore.h
sbnanaobj/StandardRecord/SRPFP.h
sbnanaobj/StandardRecord/classes_def.xml

Create SRCNNScore for adding PFP-level CNN scores

cnnscore in SR

---

sbnanaobj/StandardRecord/SRHeader.h
sbnanaobj/StandardRecord/SRTrueInteraction.h
sbnanaobj/StandardRecord/classes_def.xml

This is a copy (cherry-picked) of https://github.com/SBNSoftware/sbnanaobj/pull/124 against develop.

Adding GENIE Tree index to SRTrueInteraction [develop]

---

sbnanaobj/StandardRecord/SRHeader.h
sbnanaobj/StandardRecord/classes_def.xml

Copy of https://github.com/SBNSoftware/sbnanaobj/pull/109 but against the NuMI "release" branch.

howard spillquality numiAnalysis

---

sbnanaobj/StandardRecord/Flat/CMakeLists.txt

Copy of https://github.com/SBNSoftware/sbnanaobj/pull/114 to release/SBN2023A_NuMI

Fixing what to be installed for Flat [release/SBN2023A_NuMI]

---

sbnanaobj/StandardRecord/SRTrkMCS.h
sbnanaobj/StandardRecord/classes_def.xml

Backport to the 2023A NuMI release.

Save scatters in MCS object.

---

sbnanaobj/StandardRecord/SRTrigger.cxx
sbnanaobj/StandardRecord/SRTrigger.h
sbnanaobj/StandardRecord/classes_def.xml

Cherry-picking in what I think are the relevant commits from Gray's feature branch used in the reprocessing.

Add more info to SRTrigger.
