SBNSoftware/sbnanaobj

sbnanaobj/StandardRecord/classes_def.xml
Resolve #11 
Two notes:
* I added ClassVersion things to the enums. I don't know whether that's good or not?
* `caf::SRCRTHitMatch` and `caf::SRCRTTrackMatch` seem to be missing matching `std::vector` declarations. Don't know if that's intentional or not.
=> add ClassVersion on sbnanaobj objects

sbnanaobj/CMakeLists.txt, sbnanaobj/Morgue/CMakeLists.txt, sbnanaobj/Morgue/ParticleMatch.cxx, sbnanaobj/Morgue/ParticleMatch.h, sbnanaobj/Morgue/README, sbnanaobj/Morgue/classes.h, sbnanaobj/Morgue/classes_def.xml, sbnanaobj/StandardRecord/SRParticleMatch.cxx, sbnanaobj/StandardRecord/SRParticleMatch.h, sbnanaobj/StandardRecord/SRTrackTruth.cxx, sbnanaobj/StandardRecord/SRTrackTruth.h, sbnanaobj/StandardRecord/classes_def.xml
This PR adds the required data members in the truth match objects to store the hit and energy versions of completeness and purity.
It also takes the ParticleMatch object within SRTrackTruth and separates it as its own class SRParticleMatch.
This PR is associated with SBNSoftware/sbncode#182 which provides the functionality to fill these variables. 
The extra definitions in classes_def.xml were required to run the CAFMaker successfully.
=> Purity and Completeness of PFPs

sbnanaobj/StandardRecord/SRCRTHit.cxx, sbnanaobj/StandardRecord/SRCRTHit.h, sbnanaobj/StandardRecord/SRTrack.cxx, sbnanaobj/StandardRecord/SRTrueParticle.cxx
Whilst working on a CI test for the CAF files I came across a regular difference in supposedly "identical" files. Two values would often differ the `parent` value in `SRTrueParticle`'s and the `plane` value in `SRCRTHit`'s. 
Both of these can be solved by ensuring that the value is correctly initialised, such that if they are not filled for a particular instance they don't just take on a random value.
=> Ensure initialisations

sbnanaobj/StandardRecord/SRBNBInfo.cxx, sbnanaobj/StandardRecord/SRBNBInfo.h, sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/classes_def.xml
Add POT Accounting information for CAFs produced by BNBRetriever module. Stored in SRHeader and currently per event. More ideal would be per subrun
=> Usable POT accounting in CAFs based on BNBRetriever module

sbnanaobj/StandardRecord/SRHeader.cxx, sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/classes_def.xml
I struggled to come up with a succint name/metaphor for this concept. Anyone want to dive into a thesaurus and come up with something better than `husk`?
=> Add the hdr.husk flag to support the ability to reduce files without losing track of their POT

sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/SRNuMIInfo.cxx, sbnanaobj/StandardRecord/SRNuMIInfo.h, sbnanaobj/StandardRecord/classes_def.xml
Add in object for NuMI beamline info into the StandardRecord. Intended for the release branch
=> NuMI Spill Accounting in StandardRecord

sbnanaobj/StandardRecord/SREnums.h
`kMultisigma` added in `sbnanaobj`, followed by https://github.com/SBNSoftware/sbncode/pull/238.
=> pull/45 rebased on release/SBN2021C

ups/product_deps
This release fixes the miss-indexing issue that is the root cause of the pre-production proton PID problem
=> Update to sproxy v00.34

sbnanaobj/StandardRecord/classes_def.xml
Re discussion in the PAT meeting this afternoon.
This is a non-critical PR for SBN2022A. It will make the cafmaker stage more resilient but isn't blocking to commencing production. If there is another more significant bug found at the sbn level then this should be added to the patch, if not it doesn't need it's own patch.
The purpose of this PR is to ensure the right dictionary elements are in place to prevent cafmaker failing when fed a `-o` flag. I will make a corresponding PR for develop that will do the same and should be merged.
=> Add enums to classes_def

ups/product_deps
Fixes the problem with missing nfoo fields that affects the spill counting.
=> Upgrade to srproxy v00.35

sbnanaobj/StandardRecord/SRCRTHit.cxx, sbnanaobj/StandardRecord/SRFakeRecoParticle.cxx
Getting around to making a PR for a branch I made ages ago. Picked up in the debug builds of the CI this variable isn't initialised and so can have undefined behaviour when not filled. This makes the CI think it has changed value.
=> Initialise contained variable

sbnanaobj/StandardRecord/classes_def.xml
The dictionary for `std::vector<caf::SROpFlash>` is missing.
This has not prevented ROOT for doing the right thing, but I have found an occasion where the job would break with the related complaint, even if the issue ended up being unrelated.
To avoid misleading errors, I am asking for this dictionary to be added.
=> Added vector of SROpFlash to SR dictionaries

sbnanaobj/StandardRecord/SRHeader.cxx, sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/SRTrigger.cxx, sbnanaobj/StandardRecord/SRTrigger.h, sbnanaobj/StandardRecord/classes_def.xml
Adding trigger information in the header of the StandardRecord in order to hold the trigger information for data events and compute the time within the beam gate for data events.
Tested on ICARUS data from raw -> CAF stage and successfully computed the time within the beam gate for the data. 
Depends on equivalent PRs in icaruscode, sbncode, and sbnobj
=> Addition of trigger information in CAF files adding time within beam gate for data events

sbnanaobj/StandardRecord/SRCRUMBSResult.cxx, sbnanaobj/StandardRecord/SRCRUMBSResult.h, sbnanaobj/StandardRecord/classes_def.xml
Contains the required updates to `SRCRUMBSResult` in order to store separate signal specific versions of the CRUMBS score.
=> CRUMBS Multi Signal

sbnanaobj/StandardRecord/SRHeader.cxx, sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/classes_def.xml
All in the comment - add a flag to the header to tell if this is a blinded or prescaled file - will be used to soften the POT matching requirement in CAFAna
=> add isblind flag to header

sbnanaobj/StandardRecord/classes_def.xml
Found whilst pursuing a separate issue with the caf stage in the CI. 
We now have [vectors](https://github.com/SBNSoftware/sbnanaobj/blob/develop/sbnanaobj/StandardRecord/SRSliceRecoBranch.h#L22) of SRPFPs, which we didn't used to. This requires a vector line in the classes def file. This seemed to cause _intermittent_ issues when saving / opening caf files.
=> Add missing vector line for SRPFPs to classes def

sbnanaobj/StandardRecord/SRCRTPMTMatch.cxx, sbnanaobj/StandardRecord/SRCRTPMTMatch.h, sbnanaobj/StandardRecord/StandardRecord.h, sbnanaobj/StandardRecord/classes_def.xml
This pull request, along with sbncode PR #[353](https://github.com/SBNSoftware/sbncode/pull/353), adds a new variable to the CAFs. This
* adds a `SRCRTPMTMatch` class to the StandardRecord `SRCRTPMTMatch.{cxx,h}`
This PR is dependent on 
* icaurscode PR #[594](https://github.com/SBNSoftware/icaruscode/pull/594) 
* sbnobj PR #[86](https://github.com/SBNSoftware/sbnobj/pull/86)
* sbncode PR #[353](https://github.com/SBNSoftware/sbncode/pull/353)
=> add CRTPMT Matching variables to the StandardRecord

sbnanaobj/StandardRecord/SRCRTPMTMatch.h, sbnanaobj/StandardRecord/classes_def.xml
This PR addresses something missed my in [PR#95](https://github.com/SBNSoftware/sbnanaobj/pull/95) that was merged into develop in [v09_21_02](https://github.com/SBNSoftware/sbnanaobj/commit/f977ece2fbe88554e1ed64399645b97d5b797a67). Gianluca suggested to Enable the ROOT schema for the classes defs [ in this review comment](https://github.com/SBNSoftware/sbnanaobj/pull/97#discussion_r1239968104) on a [sbnanaobj#PR97](https://github.com/SBNSoftware/sbnanaobj/pull/97), and which #97 being a duplicate of #95 we should also add these changes here.
=> Fix checksum in `classes_def.xml` 

sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/classes_def.xml
Added a string and an index representing the name of the source of the event (typically a source file) and an index within that represents how to identify it in that source.
Matter of review by SBN!
Please add reviewer as needed (esp. from SBND).
Sibling request to _fill_ the information: SBNSoftware/sbncode#361
=> Added source file information to the standard record header

sbnanaobj/StandardRecord/SROpT0Finder.cxx, sbnanaobj/StandardRecord/SROpT0Finder.h, sbnanaobj/StandardRecord/SRSlice.h, sbnanaobj/StandardRecord/classes_def.xml
Moving OpT0 variables into the cafs. There are _two_ caf variables created: `slc.opt0` and `slc.opt0_sec`, where the latter is the "secondary" OpT0 object. 
OpT0Finder (in SBND for one-to-many matching) can output more than one match per slice if the slice is split up between two TPCs (matches are TPC specific) or if there are multiple in-time flashes. The default `slc.opt0` is filled with the OpT0 object with the **highest** OpT0 score (best match), and `slc.opt0_sec` is filled with the OpT0 object with the **second highest** OpT0 score. 
For flash-matching, looking at `slc.opt0` would be sufficient. For Q->L charge-likelihood studies, one would likely want information from both TPCs (so look at both `slc.opt0` and `slc.opt0_sec`). 
Accompanying PR in sbncode …
=> opt0finder objects in cafmaker

sbnanaobj/StandardRecord/SRHeader.h
SRProxy prior to 0.41 doesn't support static data in the class.
I am turning the static constant I put into a static function for the time being.
The `develop` branch already uses an updated SRProxy (`v0.42` at this time).
This commit should not survive into the development branch and it must be **reverted** when it lands there.
Also bound to SBNSoftware/sbncode#380 PR (since this is effectively an interface change).
=> Remove the constant from SRHeader object [1/2] [SBN2023A]

sbnanaobj/StandardRecord/SRSlice.h, sbnanaobj/StandardRecord/classes_def.xml
- Added OpFlashes to SimpleFlash for SBND and ICARUS
- Added XARAPUCA flashes to SimpleFlash for SBND
- - 2/4 flashes/slice in ICARUS/SBND
- - Each slice has seperate training metrics
- SRSlice updated to account for extra slices
=> Added OpFlashes and XARAPUCA flashes to SimpleFlash

sbnanaobj/StandardRecord/SRPFOChar.cxx, sbnanaobj/StandardRecord/SRPFOChar.h, sbnanaobj/StandardRecord/classes_def.xml
This PR contains the new variables for the new training for track vs shower discrimination in Pandora automatic reconstruction (i.e. LArBdtPfoCharacterisation) based on ICARUS bnb simulations (icaruscode v09_72_01) and including three new BDT variables.
This PR should also include changes to branches with the same name of the following repositories:
feature/acampani_sdellepi_new_BdtPfoCharacterisation in icaruscode (PR#656)
feature/acampani_sdellepi_new_BdtPfoCharacterisation in sbncode
the new BDT training .xml file in icarus_data/icarus_data/PandoraMVAs/PandoraBdt_v09_72_01_ICARUS_pfochar_bnb.xml
=> New ICARUS training for track vs shower discrimination Pandora BDT

sbnanaobj/StandardRecord/SRHeader.cxx, sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/classes_def.xml
Add variables to SRHeader to save offbeam gate count. These should be doubles due to the correction made to account for minbias events.
=> Add offbeam gate count to SRHeader

sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/SRTrueInteraction.h, sbnanaobj/StandardRecord/classes_def.xml
Adding a new `size_t` variable into `SRTrueInteraction` which corresponds to the index of the corresponding `genie::EventRecord` from the newly added GENIE tree into caf (https://github.com/SBNSoftware/sbncode/pull/426).
The matching between SRTrueInteraction object from `recTree` and `genie::EventRecord` can be done by this index.
=> Adding GENIE Tree index to SRTrueInteraction [release/SBN2023A_NuMI_2]

sbnanaobj/StandardRecord/SRTrueInteraction.cxx
@RachelCoackley made this fix a couple of weeks back but is now on her holidays. It came up in the context of the CI but is also just generally the right thing to do.
Given it's very simple I've taken the liberty of turning her branch into a PR so it doesn't miss the next release. This will mean this branch doesn't need specifying for every CI build which is a little annoying.
=> Rachel's Fix for CI

sbnanaobj/StandardRecord/SRHeader.cxx, sbnanaobj/StandardRecord/SRTrueInteraction.cxx
Setting default values for one of the new variables we added to prevent failure in CI validation. Here I cherry-picked from the commits made for https://github.com/SBNSoftware/sbnanaobj/pull/131 for develop branch.
=> Having defaults for sourceNameHash and genie_evtrec_idx

sbnanaobj/StandardRecord/SRHeader.cxx, sbnanaobj/StandardRecord/SRHeader.h, sbnanaobj/StandardRecord/SRTrueInteraction.cxx, sbnanaobj/StandardRecord/SRTrueInteraction.h, sbnanaobj/StandardRecord/classes_def.xml
This is a copy of https://github.com/SBNSoftware/sbnanaobj/pull/128  (on develop) or https://github.com/SBNSoftware/sbnanaobj/pull/124  (on release/SBN2023A_NuMI).
Adding a new `size_t genie_evtrec_idx` variable into `SRTrueInteraction` which corresponds to the index of the corresponding `genie::EventRecord`.
Also added `std::uint32_t sourceNameHash`, where we save the truncated hash of `sourceName`; this can be used when matching to auxiliary trees other than `recTree`.
=> Adding GENIE Tree index to SRTrueInteraction [release/SBN2024A]

sbnanaobj/StandardRecord/SRShower.cxx, sbnanaobj/StandardRecord/SRTrack.cxx
Setting default values for `trk.bestplane` and `shw.producer`. When the sbnd CI was being ran differences in the caf stage were appearing due to these variables not being initialised with a default value. Warnings looked like:
```
664:   rec.slc[0].reco.pfp[0].shw.producer differs: 632172960 vs 622129504
665:   rec.slc[0].reco.pfp[0].trk.bestplane differs: 786776544 vs -1706641423
```
This change sets default values for these variables, removing this warning from the CI.
=> Setting default values for variables

sbnanaobj/StandardRecord/SROpFlash.cxx, sbnanaobj/StandardRecord/SROpFlash.h, sbnanaobj/StandardRecord/classes_def.xml
This PR adds the attribute tpc into the SROpFlash object. This is required for saving the OpFlash information in SBND in CAF files.
=> Add tpc attribute to SROpFlash

sbnanaobj/StandardRecord/SRCRTHitMatch.cxx, sbnanaobj/StandardRecord/SRCRTHitMatch.h, sbnanaobj/StandardRecord/classes_def.xml
This PR adds additional information on the Standard Record: SRCRTHitMatch which are useful for the analyzers.
=> Extended information on the CRTHitT0Matching

sbnanaobj/StandardRecord/SRCRUMBSResult.cxx
@nathanielerowe pointed out some CI tests were showing variation in the opt0 variables in the CAFs CRUMBS object.
Theory that this results from the lack of initialisation of these variables (seems highly likely). Looks like I never added the initialisation when CRUMBS was updated to use OpT0 as well as SimpleFlash. This PR fixes that.
=> Initialise opt0 vars in CRUMBS result

sbnanaobj/StandardRecord/SRNuGraphScore.cxx, sbnanaobj/StandardRecord/SRNuGraphScore.h, sbnanaobj/StandardRecord/SRPFP.h, sbnanaobj/StandardRecord/SRSlice.h, sbnanaobj/StandardRecord/classes_def.xml
This PR adds a few NuGraph-related variables to CAFs, along the lines of what presented on [docdb 40585](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=40585). Once SBNSoftware/icaruscode#815 is merged the needed data products can be produced, but it won't break CAF making if they are not there. The related SBNSoftware/sbncode#532 is also being made.
=> add first NuGraph2 info to CAF

sbnanaobj/StandardRecord/SROpFlash.cxx, sbnanaobj/StandardRecord/SROpFlash.h, sbnanaobj/StandardRecord/classes_def.xml
This pull request adds a new variable to SROpFlash where the OpFlash time wrt the RWM time will be stored. Having this variable at the CAF level allows us to reconstruct the Beam Bunch structure seen by ICARUS PMTs. 
This PR is a companion to sbncode PR ### and will require [icaruscode PR #832](https://github.com/SBNSoftware/icaruscode/pull/832) and  [sbnobj PR #130 ](https://github.com/SBNSoftware/sbnobj/pull/130) to also be merged.
=> Add PMT Beam Signal timing to ICARUS CAFs 

sbnanaobj/StandardRecord/SRCaloPoint.cxx, sbnanaobj/StandardRecord/SRCaloPoint.h, sbnanaobj/StandardRecord/classes_def.xml
adding efield and phi to SRCaloPoint for 2025A
This is for the sbncode [PR559](https://github.com/SBNSoftware/sbncode/pull/559).
=> adding efield and phi to SRCaloPoint for 2025A
